### ISSUE TITLE
fastlane-plugin-simctl uses old version

### ISSUE THREAD

**Issue by niveus** [plu/simctl#31]
I followed the instructions on [this page](https://github.com/plu/simctl/blob/master/fastlane-plugin-simctl/README.md). When I run `bundle install --deployment`, it says `Installing fastlane-plugin-simctl 0.2.0` despite saying `Installing simctl 1.6.5` above it. The file `vendor/bundle/ruby/2.4.0/gems/fastlane-plugin-simctl-0.2.0/lib/fastlane/plugin/simctl/helper/simctl_helper.rb ` contains the old version of that file instead of the one that is bundled with 1.6.5. The source for the plugin is also installed under `vendor/bundle/ruby/2.4.0/gems/simctl-1.6.5/fastlane-plugin-simctl/` but it seems to be using the source from the plugin folder. 

It seems fastlane-plugin-simctl needs to also be updated and pushed to Rubygems.org

**Comment by plu** [comment]
Pushed fastlane-plugin-simctl 0.2.1 to rubygems.org
