### ISSUE TITLE
Add support for taking screenshots

### ISSUE THREAD

**Issue by stupergenius** [plu/simctl#9]
As of Xcode 8.2, we can now take screenshots through the `simctl` tool by doing something like:

```shell
$ xcrun simctl io booted screenshot
```

It would be nice if the gem also provided an interface for grabbing this screenshot, with options to save to a named file, but perhaps also to grab the bytes from stdout.

I imagine a new method on the `Device` class would be something like:

```ruby
device.screenshot(type: "png", filename: "foo.png")
```

**Comment by plu** [comment]
Change is on `master`:

```ruby
@device.screenshot!("/tmp/screenshot.png")

# Should also support, but untested:
@device.screenshot!("/tmp/screenshot.png", type: "bmp", display: "tv")
```

**Comment by stupergenius** [comment]
Thanks! 💯
